### ISSUE TITLE
Npm install fails

### ISSUE THREAD

**Issue by netdown** [jpiazzal/ts2doc#3]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @ts2doc/components@0.3.0
npm WARN Found: peer @ts2doc/json@"^0.0.1" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @ts2doc/json@"^0.0.1" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ts2doc/json@^0.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by jpiazzal** [comment]
Hi @netdown,
Can you send me more information about you problem?
- What is your environment (node version / npm version)?
- What did you do to have this error?
- What version of @ts2doc are you trying to use?

Tank you!

**Comment by jpiazzal** [comment]
Bug appears on version 0.3.0, it has been fixed on this revision: https://github.com/jpiazzal/ts2doc/commit/1652edff3c43ea5358616639f634592417e8a8a0

Version 0.3.2 fix this issue
